name: 'Ping-Code: notify'
description: 'Send a notification to Ping Code'
author: 'MagicBell'

runs:
  using: 'node16'
  main: '../dist/notify.js'

inputs:
  title:
    description: 'Notification title'
    required: true
  content:
    description: 'Notification content'
  recipients:
    description: 'Comma-separated list of recipient GitHub usernames'
    required: true
  category:
    description: 'Notification category, either if Funky, Info, warn, error'
  topic:
    description: 'Notification topic'
  action-url:
    description: 'Notification action URL'
  icon-url:
    description: 'Notification icon URL'
